from models import client

from prompts import (
    SYSTEM_PROMPTS,
    PROMPT_VERSIONS,
    build_research_prompt,
)

from tools.company_overview import get_company_overview
from tools.financials_tool import get_financial_statements
from tools.news_tool import get_company_news

from schemas.memo_schema import EquityResearchMemo


def gather_research_data(ticker: str) -> dict:
    """
    Collect research data from all tools.
    """

    company_data = get_company_overview(ticker)

    financial_data = get_financial_statements(ticker)

    news_data = get_company_news(ticker)

    return {
        "company_overview": company_data.model_dump(),
        "financials": financial_data,
        "news": [article.model_dump() for article in news_data],
    }


def generate_research_memo(
    ticker: str,
    prompt_version: str = "v3"
) -> EquityResearchMemo:
    """
    Generate structured equity research memo.
    """

    print("\n" + "=" * 60)
    print(f"Using Prompt Version: {prompt_version}")
    print(f"Prompt Style: {PROMPT_VERSIONS[prompt_version]}")
    print("=" * 60)

    research_data = gather_research_data(ticker)

    prompt = build_research_prompt(
        ticker=ticker,
        data=research_data,
        version=prompt_version
    )

    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=1500,
        temperature=0.2,
        system=SYSTEM_PROMPTS[prompt_version],
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    memo_text = response.content[0].text

    return EquityResearchMemo(
        ticker=ticker.upper(),
        investment_thesis=memo_text,
        bullish_signals=[],
        bearish_risks=[],
        valuation_summary="Generated by Claude",
        final_recommendation="HOLD",
        citations=["Yahoo Finance"]
    )